POST http://localhost:4000
Content-Type: application/json

{
    "query" : "query { status { health mode version } }"
}





###
POST http://library-31bw.onrender.com
Content-Type: application/json

{
    "query" : "query { status { health mode version } }"
}





###
POST http://library-31bw.onrender.com
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
    status {
        health
        mode
        version
    }
}





###
POST https://library-31bw.onrender.com
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImViZW5lemVyIGVzaCIsImlkIjoiNjQxNTY2MmJlY2E3ODE2N2Q3NTU3NDU5IiwiaWF0IjoxNjc5ODA4NTQ3LCJleHAiOjE2ODA0MTMzNDd9.U2XhVEyxFqlctYa6tqKYO2-CQ5sdDPIbb9-8FL-FB_E

query { 
    books { 
        id
        title 
        reserved 
        author 
        reservedDate 
        reservedBy { 
            id 
        } 
        reservationHistory 
        available 
        expired { 
            isExpired 
        } 
     } 
  }





###
POST https://library-31bw.onrender.com
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImViZW5lemVyIGVzaCIsImlkIjoiNjQxNTY2MmJlY2E3ODE2N2Q3NTU3NDU5IiwiaWF0IjoxNjc5ODA4NTQ3LCJleHAiOjE2ODA0MTMzNDd9.U2XhVEyxFqlctYa6tqKYO2-CQ5sdDPIbb9-8FL-FB_E

mutation ($id: ID!) {
    reserveBook(id: $id) {
      id
    title
    reservedDate
    reserved
    reservationHistory
    available
    expired {
      expiryDate
      isExpired
      timeFormate
    }
    reservedBy {
      id
    }
    }
  }

  {
    "id": "6415662deca78167d755746b"
  }





###
POST https://library-31bw.onrender.com
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImViZW5lemVyIGVzaCIsImlkIjoiNjQxNTY2MmJlY2E3ODE2N2Q3NTU3NDU5IiwiaWF0IjoxNjc5ODA4NTQ3LCJleHAiOjE2ODA0MTMzNDd9.U2XhVEyxFqlctYa6tqKYO2-CQ5sdDPIbb9-8FL-FB_E

mutation ($id: ID!) {
    releaseBook(id: $id) {
      id
    title
    reservedDate
    reserved
    reservationHistory
    available
    expired {
      expiryDate
      isExpired
      timeFormate
    }
    reservedBy {
      id
    }
    }
  }

  {
    "id": "6415662deca78167d755746b"
  }





###
POST https://library-31bw.onrender.com
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

mutation ($username: String!, $password: String!) { 
    login(username: $username, password: $password) { value id } 
    }

    {
      "username": "ebenezer esh",
      "password": "password"
    }
