services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
      MONGO_INITDB_DATABASE: the_database
    container_name: mongo-lib-dev
  api:
    image: back-lib-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    depends_on:
      - mongo
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 3331:3331
    environment:
      MONGO_URL: 'mongodb://the_username:the_password@mongo:27017/(REPLACE_ME)'
      BACKEND_URL_ONL: 'http://localhost:8080/api/'
      BE_STATUS: 'online'
      DB_PRO: 'the_database'
      DB_STATUS: 'online'
      EMAIL_SERVICE_ID: 'service_lcp53nu'
      EMAIL_TEMPLATE_ID: 'template_1gumj1e'
      JWT_EXP_TIME: '7d'
      JWT_SECRET: 'kj34l*483kLKj*&^%42jl@dkfsl'
      MAX_RESERVATION_TIME: '3-d'
      MONGODB_ATL: 'mongodb://the_username:the_password@mongo:27017/(REPLACE_ME)'
      PUBLIC_API_KEY: 'Bgn7EOGkCKW87zLNw'
      SALT_ROUNDS: '10'
      VERSION: '4.0.01'
      WS_URL_ONL: 'ws://localhost:8080/api/'
      PORT: '3331'
    container_name: back-lib-dev
  app:
    image: front-lib-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    depends_on:
      - api
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 3000:3000
    environment:
      BACKEND_URL_ONL: 'http://localhost:8080/api/'
      BE_STATUS: 'online'
      EMAIL_SERVICE_ID: 'service_lcp53nu'
      EMAIL_TEMPLATE_ID: 'template_1gumj1e'
      PUBLIC_API_KEY: 'Bgn7EOGkCKW87zLNw'
      VERSION: '4.0.01'
      WS_URL_ONL: 'ws://localhost:8080/api/'
    container_name: front-lib-dev
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-lib-dev
    depends_on:
      - app