services:
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: the_username
      MONGO_INITDB_ROOT_PASSWORD: the_password
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    container_name: mongo-prod
  redis:
    image: redis
    ports:
      - 7890:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
    container_name: redis-prod
  api:
    image: back-prod
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - redis
    ports:
      - 3331:3331
    environment:
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database
      REDIS_URL: redis://redis:6379
      PORT: 3331
      NODE_ENV: production
    container_name: back-prod
  app:
    image: front-prod
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - 3000:3000
    environment:
      REACT_APP_BACKEND_URL: '/api'
      NODE_ENV: 'production'
    container_name: front-prod
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-prod
    depends_on:
      - app